class Vif < Formula
  desc "AI video frame interpolation TUI"
  homepage "https://github.com/kesonglab/video-interpolate"
  # NOTE: this file is committed to video-interpolate as a reference of what
  # the release pipeline auto-pushes to kesonglab/homebrew-tap. The actual
  # formula is generated by GoReleaser (see .goreleaser.yaml) and pushed
  # by .github/workflows/release.yml via git over HTTPS so the multi-arch
  # shas below stay in sync with each release's checksums.txt.

  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.0/vif_0.3.0_darwin_amd64.tar.gz"
      sha256 "6509052aa3f24ad1a0226d41eaa65c480d85844a10e6985b7d372bab494d4409"

      define_method(:install) do
        bin.install "vif"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.0/vif_0.3.0_darwin_arm64.tar.gz"
      sha256 "357b6f83a7bf84ba5d7bf37d34c588d0a5975167065e053e8ed3beae6498c542"

      define_method(:install) do
        bin.install "vif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.0/vif_0.3.0_linux_amd64.tar.gz"
      sha256 "7476fe69321c218bd0168d2f9d8c5fee97aa584a044f0429284060a2dbde6d8a"

      define_method(:install) do
        bin.install "vif"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.0/vif_0.3.0_linux_arm64.tar.gz"
      sha256 "82c7e56924170914252e7b5711624031858ebb0212a24a5e91fc400c9ac86f9b"

      define_method(:install) do
        bin.install "vif"
      end
    end
  end

  test do
    system "#{bin}/vif", "version"
  end
end
