# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vif < Formula
  desc "AI video frame interpolation TUI"
  homepage "https://github.com/kesonglab/video-interpolate"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1/vif_0.3.1_darwin_amd64.tar.gz"
      sha256 "dcf8aa5d74d1f844a695bbbe2c69f599378d58e0f939265c1aa031c8b6a2e04d"

      define_method(:install) do
        bin.install "vif"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1/vif_0.3.1_darwin_arm64.tar.gz"
      sha256 "fdc066ce849b53c51632f080ddd92e974ff91ad43479de22328dc78ff3f32db8"

      define_method(:install) do
        bin.install "vif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1/vif_0.3.1_linux_amd64.tar.gz"
      sha256 "027225331216dedcffec2315488baf03a2acec8a770a96b4efb835e263ea1cfc"
      define_method(:install) do
        bin.install "vif"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1/vif_0.3.1_linux_arm64.tar.gz"
      sha256 "c10e6d16b8a8cc985ee1db920da8a57490a053fa0b32dc4c5c48c5b982b817a7"
      define_method(:install) do
        bin.install "vif"
      end
    end
  end

  test do
    system "#{bin}/vif", "version"
  end
end
